language: en
pipeline:
    -   name: SpacyNLP
        model: en_core_web_md
        case_sensitive: false
    -   name: SpacyTokenizer
    -   name: SpacyFeaturizer
    -   name: RegexFeaturizer
    -   name: "CRFEntityExtractor"
        features: [["low", "suffix1", "pos"], ["bias", "suffix5", "suffix3", "digit", "upper"], ["pos", "pos2", "suffix2"]]
        BILOU_flag: true
        max_iterations: 100
        L1_c: 0.1
        L2_c: 0.1
    -   name: SklearnIntentClassifier
    -   name: "DucklingHTTPExtractor"
        url: "http://localhost:8000"
        dimensions: ["time", "duration"]
        timezone: "Europe/Berlin"

policies:
    -   name: MemoizationPolicy
    -   name: KerasPolicy
    -   name: MappingPolicy
    -   name: FallbackPolicy
        nlu_threshold: 0.4
        core_threshold: 0.3
        fallback_action_name: action_default_fallback
